#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Set up the five GitHub secrets that .github/workflows/release-app.yml needs for Developer ID
# signing and notarization. The private key, CSR and p12 stay in ~/.vibebuddy-signing (never in the repo or .env);
# rerunning after quitting halfway reuses the private key already generated.

TOTAL_STAGES=5

cd "$(dirname "${BASH_SOURCE[0]}")/.."
# Always use the system LibreSSL: p12 files made by Homebrew's OpenSSL 3 with default settings can't be read
# by macOS's security import.
OPENSSL=/usr/bin/openssl
WORK="${HOME}/.vibebuddy-signing"
KEY="${WORK}/developer-id.key"
CSR="${WORK}/developer-id.csr"
P12="${WORK}/developer-id.p12"
mkdir -p "${WORK}"; chmod 700 "${WORK}"

banner "Vibe Buddy 发布签名配置"

stage "生成私钥与证书请求（CSR）"
say "Developer ID 证书要用一把只有你持有的私钥去申请。私钥放在 ${WORK}，"
say "以后换机器或证书到期续签都靠它，请自己另外备份一份。"
if [[ -f "${KEY}" ]]; then
  note "已有 ${KEY}，接着用。"
else
  ask CSR_EMAIL "Apple 开发者账号的邮箱（只写进 CSR）:"
  "${OPENSSL}" genrsa -out "${KEY}" 2048 2>/dev/null
  chmod 600 "${KEY}"
  "${OPENSSL}" req -new -key "${KEY}" -out "${CSR}" -subj "/emailAddress=${CSR_EMAIL}/CN=Vibe Buddy Developer ID/C=CN"
fi
[[ -f "${CSR}" ]] || "${OPENSSL}" req -new -key "${KEY}" -out "${CSR}" -subj "/CN=Vibe Buddy Developer ID/C=CN"
printf '  %s✓%s CSR: %s\n' "$GREEN" "$RESET" "${CSR}"
pause "按回车去申请证书"

stage "申请 Developer ID Application 证书"
warn "只有账号持有人（Account Holder）能建 Developer ID 证书。"
open_url "https://developer.apple.com/account/resources/certificates/add"
step "Software 一栏选「Developer ID Application」，Continue。"
step "Profile Type / Sub-CA 选「G2 Sub-CA」，Continue。"
step "Choose File 选这个文件（已拷进剪贴板，文件框里按 ⌘⇧G 粘贴）：${CSR}"
printf '%s' "${CSR}" | pbcopy 2>/dev/null || true
step "Continue → Download，得到 developerID_application.cer。"
CER=""
while [[ ! -f "${CER}" ]]; do
  ask CER_INPUT "下载好的 .cer 路径（回车用 ~/Downloads/developerID_application.cer）:"
  CER="${CER_INPUT:-${HOME}/Downloads/developerID_application.cer}"
  CER="${CER/#\~/${HOME}}"
  [[ -f "${CER}" ]] || warn "找不到 ${CER}"
done
"${OPENSSL}" x509 -inform DER -in "${CER}" -out "${WORK}/developer-id.pem"
SUBJECT="$("${OPENSSL}" x509 -in "${WORK}/developer-id.pem" -noout -subject)"
if [[ "${SUBJECT}" != *"Developer ID Application"* ]]; then
  warn "这张不是 Developer ID Application 证书：${SUBJECT}"
  exit 1
fi
# The certificate and private key must be a pair, or the exported p12 can't sign on CI.
if [[ "$("${OPENSSL}" x509 -in "${WORK}/developer-id.pem" -noout -modulus)" != "$("${OPENSSL}" rsa -in "${KEY}" -noout -modulus 2>/dev/null)" ]]; then
  warn "这张证书不是用 ${CSR} 申请的，和本机私钥对不上。"
  exit 1
fi
printf '  %s✓%s %s\n' "$GREEN" "$RESET" "${SUBJECT#subject=}"
pause "按回车打包 p12"

stage "打包 p12，写入证书相关的 secrets"
say "把私钥、证书和 Apple 的 G2 中间证书打成一个 p12，密码随机生成。"
curl -fsSL "https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer" -o "${WORK}/DeveloperIDG2CA.cer"
"${OPENSSL}" x509 -inform DER -in "${WORK}/DeveloperIDG2CA.cer" -out "${WORK}/DeveloperIDG2CA.pem"
P12_PASSWORD="$("${OPENSSL}" rand -hex 24)"
export P12_PASSWORD
"${OPENSSL}" pkcs12 -export -inkey "${KEY}" -in "${WORK}/developer-id.pem" \
  -certfile "${WORK}/DeveloperIDG2CA.pem" -name "Developer ID Application" \
  -out "${P12}" -passout env:P12_PASSWORD
chmod 600 "${P12}"
# Import it into a temporary keychain the way CI does, to confirm codesign recognizes the identity.
TEST_KEYCHAIN="${WORK}/verify.keychain-db"
security delete-keychain "${TEST_KEYCHAIN}" >/dev/null 2>&1 || true
security create-keychain -p verify "${TEST_KEYCHAIN}"
security import "${P12}" -P "${P12_PASSWORD}" -A -t cert -f pkcs12 -k "${TEST_KEYCHAIN}" >/dev/null
# The trust chain is only evaluated for keychains in the search list; without adding it, -v finds nothing (verified 2026-09-22).
SAVED_KEYCHAINS="$(security list-keychains -d user | tr -d '" ' | tr '\n' ' ')"
# shellcheck disable=SC2086
security list-keychains -d user -s "${TEST_KEYCHAIN}" ${SAVED_KEYCHAINS}
IDENTITY="$(security find-identity -v -p codesigning "${TEST_KEYCHAIN}" | sed -n 's/.*"\(Developer ID Application: .*\)"/\1/p' | head -n 1)"
# shellcheck disable=SC2086
security list-keychains -d user -s ${SAVED_KEYCHAINS}
security delete-keychain "${TEST_KEYCHAIN}"
if [[ -z "${IDENTITY}" ]]; then
  warn "p12 导得进钥匙串，但里面没有可用的签名身份，先别往下走。"
  exit 1
fi
printf '  %s✓%s 签名身份: %s\n' "$GREEN" "$RESET" "${IDENTITY}"
set_secret MACOS_CERT_P12 "$(base64 < "${P12}" | tr -d '\n')"
set_secret MACOS_CERT_PASSWORD "${P12_PASSWORD}"
note "p12 密码只存在 GitHub secret 里；要再用就重跑本脚本重新打包。"
pause

stage "Apple ID 与 Team ID"
TEAM_GUESS="$(printf '%s' "${IDENTITY}" | sed -n 's/.*(\([A-Z0-9]\{10\}\))$/\1/p')"
say "公证用你的 Apple ID 登录。Team ID 从证书里读到的是：${TEAM_GUESS:-（没读到）}"
note "核对处：https://developer.apple.com/account → Membership details → Team ID"
ask APPLE_TEAM_ID "Team ID（回车用 ${TEAM_GUESS:-上面查到的值}）:"
APPLE_TEAM_ID="${APPLE_TEAM_ID:-${TEAM_GUESS}}"
ask APPLE_ID "Apple 开发者账号的邮箱:"
set_secret APPLE_TEAM_ID "${APPLE_TEAM_ID}"
set_secret APPLE_ID "${APPLE_ID}"
pause

stage "App 专用密码"
say "公证服务不收 Apple ID 的登录密码，要一个 App 专用密码。"
open_url "https://account.apple.com/account/manage"
step "登录 → 「登录与安全」→「App 专用密码」→ 生成，名称填 vibe-buddy-notary。"
step "复制弹出来的 xxxx-xxxx-xxxx-xxxx。"
while true; do
  ask_secret APPLE_APP_PASSWORD "粘贴 App 专用密码:"
  # Actually log in to the notary service with it once; it only counts if the history can be listed.
  if xcrun notarytool history --apple-id "${APPLE_ID}" --team-id "${APPLE_TEAM_ID}" \
       --password "${APPLE_APP_PASSWORD}" >/dev/null 2>&1; then
    printf '  %s✓%s 公证服务接受这组凭据\n' "$GREEN" "$RESET"
    break
  fi
  warn "公证服务拒绝了这组 Apple ID / Team ID / 密码。"
  confirm "重新粘贴一次？" || { SKIPPED+=("GitHub secret APPLE_APP_PASSWORD（凭据未通过验证）"); break; }
done
if [[ " ${SKIPPED[*]-} " != *"APPLE_APP_PASSWORD"* ]]; then
  set_secret APPLE_APP_PASSWORD "${APPLE_APP_PASSWORD}"
fi
if (( ${#SKIPPED[@]} == 0 )) && confirm "现在就触发一次 release-app，出第一版签名加公证的 DMG？"; then
  gh workflow run release-app.yml --ref main && note "已触发，进度：gh run watch"
fi

finish
note "私钥与 p12 在 ${WORK}，请备份；这个目录不要进任何仓库。"
